config/routes.rb
Rails.application.routes.draw do
  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
  TYPES=[
    "fondo",
    "entidad",
    "cuenta"
  ].freeze

  validates :name, presence: true
  validates :account_type, inclusion: { in: TYPES,
            message: "%{value} no es un tipo de cuenta válido" }

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.order(name: :asc)
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    Account.create(account_params)
    redirect_to accounts_path
  end

  def update
    @account = Account.find(params[:id])
    @account.update_attributes(account_params)
    redirect_to accounts_path
  end

  def edit
    @account = Account.find(params[:id])
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to accounts_path
  end

  private

  def account_params
    params.require(:account).permit(:name, :description, :account_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_account.html.haml
%tr
  %td= account.name 
  %td= account.description
  %td= account.account_type
  %td
    = link_to 'Editar', edit_account_path(account)
    \/
    = link_to 'Eliminar', account_path(account), method: :delete, data: { confirm: '¿Está seguro de que desea eliminar la cuenta?' }

app/views/accounts/_fields.html.haml
.form-group
  = f.label :name
  = f.text_field :name, class:'form-control'
.form-group 
  = f.label :description
  = f.text_area :description, class:'form-control'
.form-group
  = f.label :account_type
  = f.select :account_type, Account::TYPES, {}, class:'form-control'

app/views/accounts/edit.html.haml
%h1 Editar Cuenta
.panel.panel-default
  .panel-body
    = form_for @account do |f|
      = render partial:'fields', locals:{f:f}
      = f.submit 'Guardar', class:'btn btn-primary'
= link_to 'Volver a cuentas', accounts_path

app/views/accounts/index.html.haml
%h1 Cuentas
=link_to 'Nueva cuenta', new_account_path
.panel.panel-default
  .panel-body
    %table.table
      %thead
        %tr
          %th Nombre
          %th Descripci&oacute;n
          %th Tipo
      %tbody
        = render @accounts

app/views/accounts/new.html.haml
%h1 Nueva Cuenta
.panel.panel-default
  .panel-body
    = form_for @account do |f|
      = render partial:'fields', locals:{f:f}
      = f.submit 'Crear', class:'btn btn-primary'
= link_to 'Volver a cuentas', accounts_path

app/views/accounts/show.html.haml
%h1 Accounts#show
%p Find me in app/views/accounts/show.html.haml

app/views/accounts/update.html.haml
%h1 Accounts#update
%p Find me in app/views/accounts/update.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tesoreria
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield